# numpy unique values

In [3]:
import numpy as np

In [5]:
# syntax:nuumpy.unique(ndarray,return_index=False,return_counts=False,axis=None)

In [7]:
arr=np.array([10,11,12,13,11,1,18,12,13,19,32,10])
unique=np.unique(arr)
print(unique)

[ 1 10 11 12 13 18 19 32]


In [9]:
arr=np.array([10,11,12,13,11,1,18,12,13,19,32,10])
unique,index=np.unique(arr,return_index=True)
print(unique)
print(index)

[ 1 10 11 12 13 18 19 32]
[ 5  0  1  2  3  6  9 10]


In [11]:
arr=np.array([10,11,12,13,11,1,18,12,13,19,32,10])
unique=np.unique(arr,return_index=True)
print(unique[0])
print(unique[1])

[ 1 10 11 12 13 18 19 32]
[ 5  0  1  2  3  6  9 10]


In [17]:
# find the unique values and index values and zip them 
arr=np.array([10,11,12,13,11,1,18,12,13,19,32,10])
unique,index=np.unique(arr,return_index=True)
print("values\tindex")
for uni,ind in zip(unique,index):
    print("{}\t{}".format(uni,ind))

values	index
1	5
10	0
11	1
12	2
13	3
18	6
19	9
32	10


In [21]:
# finding the unique values and index and counts
arr=np.array([10,11,12,13,11,1,18,12,13,19,32,10])
uic=np.unique(arr,return_index=True,return_counts=True)
print("unique value:{}".format(uic[0]))
print("index values:{}".format(uic[1]))
print("values count:{}".format(uic[2]))

unique value:[ 1 10 11 12 13 18 19 32]
index values:[ 5  0  1  2  3  6  9 10]
values count:[1 2 2 2 2 1 1 1]


# 2-d array

In [24]:
arr=np.array([[11,11,12,11],[13,11,12,11],[16,11,12,11],[11,11,12,11]])
print(arr)

[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]


In [32]:
uni=np.unique(arr,return_index=True,return_counts=True)
print(uni[0])
print(uni[1])
print(uni[2])

[11 12 13 16]
[0 2 4 8]
[10  4  1  1]


In [36]:
uni=np.unique(arr,return_index=True,return_counts=True,axis=0)
print("unique values:{}".format(uni[0]))
print("index values:{}".format(uni[1]))
print("value counts:{}".format(uni[2]))

unique values:[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]
index values:[0 1 2]
value counts:[2 1 1]


In [40]:
uni=np.unique(arr,return_index=True,return_counts=True,axis=1)
print("unique values:{}/n".format(uni[0]))
print("index values:{}".format(uni[1]))
print("value counts:{}".format(uni[2]))

unique values/n:[[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]/n
index values:[1 0 2]
value counts:[2 1 1]
