# statistical operations

In [2]:
import numpy as np

In [4]:
# amax(),amin(),mean(),median(),var(),std() here the axis=0 is column,and axis=1 is row 

In [6]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82])
mele=np.amax(arr)
print(mele)

82


In [8]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82])
mele=np.amin(arr)
print(mele)

12


In [18]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82,72,56,31,67]).reshape(4,4)
print(arr)
mele=np.amax(arr,axis=0)
print(mele)

[[78 12 22 44]
 [32 43 57 75]
 [74 73 43 82]
 [72 56 31 67]]
[78 73 57 82]


In [20]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82,72,56,31,67]).reshape(4,4)
print(arr)
mele=np.amin(arr,axis=0)
print(mele)

[[78 12 22 44]
 [32 43 57 75]
 [74 73 43 82]
 [72 56 31 67]]
[32 12 22 44]


In [22]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82,72,56,31,67]).reshape(4,4)
print(arr)
mele=np.amax(arr,axis=1)
print(mele)

[[78 12 22 44]
 [32 43 57 75]
 [74 73 43 82]
 [72 56 31 67]]
[78 75 82 72]


In [24]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82,72,56,31,67]).reshape(4,4)
print(arr)
mele=np.amin(arr,axis=1)
print(mele)

[[78 12 22 44]
 [32 43 57 75]
 [74 73 43 82]
 [72 56 31 67]]
[12 32 43 31]


In [26]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82])
np.mean(arr)

52.916666666666664

In [30]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82])
np.median(arr)

50.5

In [32]:
np.var(arr)

514.2430555555555

In [34]:
np.std(arr)

22.676927824455312

In [36]:
arr=np.array([78,12,22,44,32,43,57,75,74,73,43,82,72,56,31,67]).reshape(4,4)
print(arr)

[[78 12 22 44]
 [32 43 57 75]
 [74 73 43 82]
 [72 56 31 67]]


In [38]:
np.mean(arr)

53.8125

In [40]:
np.mean(arr,axis=0)

array([64.  , 46.  , 38.25, 67.  ])

In [42]:
np.mean(arr,axis=1)

array([39.  , 51.75, 68.  , 56.5 ])

In [44]:
np.median(arr,axis=0)

array([73. , 49.5, 37. , 71. ])

In [46]:
np.median(arr,axis=1)

array([33. , 50. , 73.5, 61.5])

In [48]:
np.var(arr,axis=0)

array([346.    , 498.5   , 172.6875, 204.5   ])

In [50]:
np.var(arr,axis=1)

array([641.    , 258.6875, 220.5   , 250.25  ])

In [52]:
np.std(arr,axis=0)

array([18.60107524, 22.32711356, 13.1410616 , 14.30034965])

In [54]:
np.std(arr,axis=1)

array([25.3179778 , 16.08376511, 14.8492424 , 15.81929202])

In [58]:
import statistics as s

In [68]:
s.mode([11,23,24,56,10,10,11])

11

In [72]:
s.multimode([11,23,24,56,10,10,11])

[11, 10]